const products = [
  {
    id: "creed-aventus",
    brand: "Creed",
    name: "Aventus",
    concentration: "EDP",
    releaseYear: 2010,
    perfumer: "Olivier Creed",
    description: "A masterpiece of modern perfumery, Aventus celebrates strength, vision, and success. Inspired by the dramatic life of a historic emperor, this fragrance opens with bold pineapple and bergamot, developing into a heart of birch and jasmine, resting on a base of musk and oakmoss.",
    notes: { top: ["Pineapple", "Bergamot", "Black Currant", "Apple"], middle: ["Birch", "Jasmine", "Rose"], base: ["Musk", "Oakmoss", "Ambergris", "Vanilla"] },
    family: "Fruity Woody",
    image: "images/aventus.jpg",
    images: ["images/aventus.jpg", "images/aventus-2.jpg"],
    sizes: [{ ml: 2, price: 750, inStock: true }, { ml: 5, price: 1500, inStock: true }, { ml: 10, price: 2800, inStock: true }, { ml: 20, price: 5200, inStock: true }],
    isDecant: true, featured: true, rating: 4.9, reviews: 234
  },
  {
    id: "nishane-hacivat",
    brand: "Nishane",
    name: "Hacivat",
    concentration: "EDP",
    releaseYear: 2017,
    perfumer: "Jorge Lee",
    description: "Hacivat is a luxurious chypre fragrance that pays homage to the iconic Turkish puppeteer. A vibrant burst of pineapple and grapefruit leads into a heart of cedar and patchouli, with a base of oakmoss and musk that lingers magnificently.",
    notes: { top: ["Pineapple", "Grapefruit", "Bergamot"], middle: ["Cedar", "Patchouli", "Jasmine"], base: ["Oakmoss", "Musk", "Amber", "Sandalwood"] },
    family: "Chypre Fruity",
    image: "images/hacivat.jpg",
    images: ["images/hacivat.jpg", "images/hacivat-2.jpg"],
    sizes: [{ ml: 2, price: 650, inStock: true }, { ml: 5, price: 1400, inStock: true }, { ml: 10, price: 2600, inStock: true }, { ml: 20, price: 4800, inStock: true }],
    isDecant: true, featured: true, rating: 4.8, reviews: 156
  },
  {
    id: "xerjoff-naxos",
    brand: "Xerjoff",
    name: "Naxos",
    concentration: "EDP",
    releaseYear: 2015,
    perfumer: "Chris Maurice",
    description: "Inspired by the Italian island of Naxos, this fragrance captures the essence of Mediterranean luxury. A harmonious blend of honey, tobacco, and lavender creates a sophisticated and seductive scent profile that evolves beautifully.",
    notes: { top: ["Bergamot", "Lemon", "Lavender"], middle: ["Honey", "Tobacco", "Cinnamon", "Jasmine"], base: ["Vanilla", "Tonka", "Sandalwood", "Musk"] },
    family: "Oriental Fougere",
    image: "images/naxos.jpg",
    images: ["images/naxos.jpg", "images/naxos-2.jpg"],
    sizes: [{ ml: 2, price: 700, inStock: true }, { ml: 5, price: 1600, inStock: true }, { ml: 10, price: 3000, inStock: true }, { ml: 20, price: 5500, inStock: true }],
    isDecant: true, featured: true, rating: 4.7, reviews: 142
  },
  {
    id: "amouage-interlude",
    brand: "Amouage",
    name: "Interlude",
    concentration: "EDP",
    releaseYear: 2012,
    perfumer: "Pierre Negrin",
    description: "A bold and smoky masterpiece from the house of Amouage. Interlude is a complex oriental fragrance featuring oregano, frankincense, and amber. Dark, mysterious, and incredibly long-lasting, it commands attention.",
    notes: { top: ["Oregano", "Bergamot", "Pomegranate"], middle: ["Frankincense", "Olibanum", "Opoponax"], base: ["Leather", "Amber", "Myrrh", "Sandalwood"] },
    family: "Oriental Spicy",
    image: "images/interlude.jpg",
    images: ["images/interlude.jpg", "images/interlude-2.jpg"],
    sizes: [{ ml: 2, price: 800, inStock: true }, { ml: 5, price: 1800, inStock: true }, { ml: 10, price: 3400, inStock: true }, { ml: 20, price: 6200, inStock: true }],
    isDecant: true, featured: true, rating: 4.6, reviews: 98
  },
  {
    id: "pdM-layton",
    brand: "Parfums de Marly",
    name: "Layton",
    concentration: "EDP",
    releaseYear: 2016,
    perfumer: "Hamid Merati-Kashani",
    description: "Layton embodies the elegance and refinement of the 18th century. A stunning blend of apple, lavender, and vanilla with a woody base creates a fragrance that is both modern and timeless.",
    notes: { top: ["Apple", "Lavender", "Bergamot"], middle: ["Jasmine", "Rose", "Geranium"], base: ["Vanilla", "Sandalwood", "Guaiac Wood", "Musk"] },
    family: "Oriental Woody",
    image: "images/layton.jpg",
    images: ["images/layton.jpg", "images/layton-2.jpg"],
    sizes: [{ ml: 2, price: 700, inStock: true }, { ml: 5, price: 1500, inStock: true }, { ml: 10, price: 2800, inStock: true }, { ml: 20, price: 5100, inStock: true }],
    isDecant: true, featured: true, rating: 4.8, reviews: 189
  },
  {
    id: "mancera-cedrat-boise",
    brand: "Mancera",
    name: "Cedrat Boise",
    concentration: "EDP",
    releaseYear: 2011,
    perfumer: "Pierre Montale",
    description: "A vibrant and fresh interpretation of the woody citrus family. Cedrat Boise opens with a burst of lemon and black currant, developing into a heart of cedar and leather, resting on a base of woody notes and musk.",
    notes: { top: ["Lemon", "Black Currant", "Bergamot"], middle: ["Cedar", "Leather", "Jasmine"], base: ["Wood", "Musk", "Amber", "Oakmoss"] },
    family: "Woody Citrus",
    image: "images/cedrat-boise.jpg",
    images: ["images/cedrat-boise.jpg", "images/cedrat-boise-2.jpg"],
    sizes: [{ ml: 2, price: 550, inStock: true }, { ml: 5, price: 1200, inStock: true }, { ml: 10, price: 2300, inStock: true }, { ml: 20, price: 4200, inStock: true }],
    isDecant: true, featured: false, rating: 4.5, reviews: 87
  },
  {
    id: "montale-arabians-tonka",
    brand: "Montale",
    name: "Arabians Tonka",
    concentration: "EDP",
    releaseYear: 2015,
    perfumer: "Pierre Montale",
    description: "A rich and opulent oriental fragrance that captures the essence of Arabian luxury. Saffron and cinnamon lead to a heart of oud and tonka bean, creating a warm, seductive, and unforgettable scent.",
    notes: { top: ["Saffron", "Cinnamon", "Cardamom"], middle: ["Oud", "Tonka", "Amber"], base: ["Vanilla", "Musk", "Sandalwood", "Benzoin"] },
    family: "Oriental Gourmand",
    image: "images/arabians-tonka.jpg",
    images: ["images/arabians-tonka.jpg", "images/arabians-tonka-2.jpg"],
    sizes: [{ ml: 2, price: 600, inStock: true }, { ml: 5, price: 1300, inStock: true }, { ml: 10, price: 2500, inStock: true }, { ml: 20, price: 4600, inStock: true }],
    isDecant: true, featured: false, rating: 4.6, reviews: 112
  },
  {
    id: "mfk-baccarat-rouge-540",
    brand: "Maison Francis Kurkdjian",
    name: "Baccarat Rouge 540",
    concentration: "EDP",
    releaseYear: 2015,
    perfumer: "Francis Kurkdjian",
    description: "An iconic fragrance that has achieved legendary status. A unique blend of saffron, jasmine, and ambergris creates a luminous and mesmerizing scent. The ambergris base provides an unparalleled radiance.",
    notes: { top: ["Saffron", "Jasmine"], middle: ["Ambergris", "Cedar"], base: ["Fir", "Musk", "Amber"] },
    family: "Ambery Woody",
    image: "images/baccarat-rouge.jpg",
    images: ["images/baccarat-rouge.jpg", "images/baccarat-rouge-2.jpg"],
    sizes: [{ ml: 2, price: 900, inStock: true }, { ml: 5, price: 2000, inStock: true }, { ml: 10, price: 3800, inStock: true }, { ml: 20, price: 7000, inStock: true }],
    isDecant: true, featured: true, rating: 4.9, reviews: 312
  },
  {
    id: "roja-enigma",
    brand: "Roja Parfums",
    name: "Enigma Pour Homme",
    concentration: "Parfum",
    releaseYear: 2013,
    perfumer: "Roja Dove",
    description: "A masterpiece of British perfumery. Enigma is a sophisticated blend of cognac, tobacco, and vanilla that creates a warm, intoxicating, and elegant scent. The finest ingredients from around the world.",
    notes: { top: ["Bergamot", "Cognac", "Pink Pepper"], middle: ["Tobacco", "Jasmine", "Rose"], base: ["Vanilla", "Oakmoss", "Amber", "Musk"] },
    family: "Oriental Woody",
    image: "images/enigma.jpg",
    images: ["images/enigma.jpg", "images/enigma-2.jpg"],
    sizes: [{ ml: 2, price: 950, inStock: true }, { ml: 5, price: 2200, inStock: true }, { ml: 10, price: 4000, inStock: true }, { ml: 20, price: 7500, inStock: true }],
    isDecant: true, featured: false, rating: 4.7, reviews: 76
  },
  {
    id: "initio-side-effect",
    brand: "Initio",
    name: "Side Effect",
    concentration: "EDP",
    releaseYear: 2018,
    perfumer: "Unknown",
    description: "A dangerously addictive fragrance from Initio. Side Effect combines rum, saffron, and tobacco with vanilla for a warm, spicy, and seductive experience. The cherry-like note from rum and saffron is intoxicating.",
    notes: { top: ["Rum", "Saffron", "Cinnamon"], middle: ["Tobacco", "Birch", "Juniper"], base: ["Vanilla", "Amber", "Musk", "Sandalwood"] },
    family: "Oriental Spicy",
    image: "images/side-effect.jpg",
    images: ["images/side-effect.jpg", "images/side-effect-2.jpg"],
    sizes: [{ ml: 2, price: 750, inStock: true }, { ml: 5, price: 1700, inStock: true }, { ml: 10, price: 3200, inStock: true }, { ml: 20, price: 5900, inStock: true }],
    isDecant: true, featured: false, rating: 4.7, reviews: 134
  },
  {
    id: "lv-imagination",
    brand: "Louis Vuitton",
    name: "Imagination",
    concentration: "EDP",
    releaseYear: 2021,
    perfumer: "Jacques Cavallier",
    description: "A masterful creation from Louis Vuitton's in-house perfumer. Imagination is a sparkling citrus fragrance with tea and ginger notes that create an invigorating and sophisticated aura.",
    notes: { top: ["Bergamot", "Ginger", "Citrus"], middle: ["Tea", "Incense", "Neroli"], base: ["Amber", "Musk", "Cedar", "Sandalwood"] },
    family: "Citrus Aromatic",
    image: "images/imagination.jpg",
    images: ["images/imagination.jpg", "images/imagination-2.jpg"],
    sizes: [{ ml: 2, price: 850, inStock: true }, { ml: 5, price: 1900, inStock: true }, { ml: 10, price: 3600, inStock: true }, { ml: 20, price: 6600, inStock: true }],
    isDecant: true, featured: true, rating: 4.8, reviews: 203
  },
  {
    id: "tf-tobacco-vanille",
    brand: "Tom Ford",
    name: "Tobacco Vanille",
    concentration: "EDP",
    releaseYear: 2007,
    perfumer: "Olivier Gillotin",
    description: "A modern classic from Tom Ford's Private Blend collection. Tobacco Vanille is a rich, warm, and opulent fragrance that combines sweet vanilla with smoky tobacco, creating one of the most beloved gourmand scents.",
    notes: { top: ["Tobacco", "Vanilla", "Chocolate"], middle: ["Tonka", "Cocoa", "White Honey"], base: ["Dried Fruits", "Wood", "Musk"] },
    family: "Gourmand Spicy",
    image: "images/tobacco-vanille.jpg",
    images: ["images/tobacco-vanille.jpg", "images/tobacco-vanille-2.jpg"],
    sizes: [{ ml: 2, price: 700, inStock: true }, { ml: 5, price: 1500, inStock: true }, { ml: 10, price: 2900, inStock: true }, { ml: 20, price: 5400, inStock: true }],
    isDecant: true, featured: true, rating: 4.8, reviews: 267
  },
  {
    id: "dior-sauvage-elixir",
    brand: "Dior",
    name: "Sauvage Elixir",
    concentration: "Elixir",
    releaseYear: 2021,
    perfumer: "Francois Demachy",
    description: "The most intense interpretation of Sauvage. Elixir is a concentrated, powerful, and profoundly aromatic fragrance that pushes the boundaries of perfumery with its rich and spicy composition.",
    notes: { top: ["Cinnamon", "Nutmeg", "Grapefruit"], middle: ["Sage", "Lavender", "Cardamom"], base: ["Sandalwood", "Licorice", "Amber", "Cedar"] },
    family: "Aromatic Spicy",
    image: "images/sauvage-elixir.jpg",
    images: ["images/sauvage-elixir.jpg", "images/sauvage-elixir-2.jpg"],
    sizes: [{ ml: 2, price: 650, inStock: true }, { ml: 5, price: 1400, inStock: true }, { ml: 10, price: 2600, inStock: true }, { ml: 20, price: 4800, inStock: true }],
    isDecant: true, featured: false, rating: 4.6, reviews: 178
  },
  {
    id: "chanel-bleu",
    brand: "Chanel",
    name: "Bleu de Chanel",
    concentration: "EDP",
    releaseYear: 2014,
    perfumer: "Jacques Polge",
    description: "A timeless icon of modern perfumery. Bleu de Chanel is a woody aromatic fragrance that embodies freedom and masculinity. The EDP concentration offers deeper richness and longevity.",
    notes: { top: ["Grapefruit", "Ginger", "Mint", "Lemon"], middle: ["Incense", "Jasmine", "Nutmeg"], base: ["Cedar", "Sandalwood", "Amber", "Musk"] },
    family: "Woody Aromatic",
    image: "images/bleu-de-chanel.jpg",
    images: ["images/bleu-de-chanel.jpg", "images/bleu-de-chanel-2.jpg"],
    sizes: [{ ml: 2, price: 550, inStock: true }, { ml: 5, price: 1200, inStock: true }, { ml: 10, price: 2200, inStock: true }, { ml: 20, price: 4000, inStock: true }],
    isDecant: true, featured: false, rating: 4.7, reviews: 345
  },
  {
    id: "creed-green-irish-tweed",
    brand: "Creed",
    name: "Green Irish Tweed",
    concentration: "EDP",
    releaseYear: 1985,
    perfumer: "Olivier Creed",
    description: "A legendary aromatic fougere and the epitome of elegance. Green Irish Tweed opens with a burst of lemon and verbena over a heart of orris and violet leaf, resting on a base of sandalwood and ambergris. Timeless, refined, and effortlessly sophisticated.",
    notes: { top: ["Lemon", "Verbena", "Mint"], middle: ["Iris", "Violet Leaf", "Orris"], base: ["Sandalwood", "Ambergris", "Cedar"] },
    family: "Aromatic Fougere",
    image: "images/green-irish-tweed.jpg",
    images: ["images/green-irish-tweed.jpg", "images/green-irish-tweed-2.jpg"],
    sizes: [{ ml: 2, price: 700, inStock: true }, { ml: 5, price: 1500, inStock: true }, { ml: 10, price: 2800, inStock: true }, { ml: 20, price: 5100, inStock: true }],
    isDecant: true, featured: true, rating: 4.8, reviews: 198
  },
  {
    id: "creed-silver-mountain-water",
    brand: "Creed",
    name: "Silver Mountain Water",
    concentration: "EDP",
    releaseYear: 1995,
    perfumer: "Olivier Creed",
    description: "Inspired by the pristine Alpine springs, Silver Mountain Water is a crisp, cool aquatic fragrance with notes of bergamot, black currant, and green tea. A refreshing and sophisticated scent that evokes mountain breezes and crystal-clear waters.",
    notes: { top: ["Bergamot", "Mandarin", "Green Tea"], middle: ["Black Currant", "Galbanum", "Petitgrain"], base: ["Sandalwood", "Musk", "Cedar"] },
    family: "Aromatic Aquatic",
    image: "images/silver-mountain-water.jpg",
    images: ["images/silver-mountain-water.jpg", "images/silver-mountain-water-2.jpg"],
    sizes: [{ ml: 2, price: 700, inStock: true }, { ml: 5, price: 1500, inStock: true }, { ml: 10, price: 2800, inStock: true }, { ml: 20, price: 5100, inStock: true }],
    isDecant: true, featured: false, rating: 4.6, reviews: 167
  },
  {
    id: "tf-oud-wood",
    brand: "Tom Ford",
    name: "Oud Wood",
    concentration: "EDP",
    releaseYear: 2007,
    perfumer: "Richard Herpin",
    description: "A modern classic from Tom Ford's Private Blend. Oud Wood is a sophisticated and alluring blend of exotic oud, sandalwood, and spices. Warm, woody, and impeccably refined, it is the perfect introduction to oud-based fragrances.",
    notes: { top: ["Cardamom", "Rosewood", "Chinese Pepper"], middle: ["Oud", "Sandalwood", "Cedar"], base: ["Vanilla", "Amber", "Tonka", "Musk"] },
    family: "Woody Spicy",
    image: "images/oud-wood.jpg",
    images: ["images/oud-wood.jpg", "images/oud-wood-2.jpg"],
    sizes: [{ ml: 2, price: 750, inStock: true }, { ml: 5, price: 1700, inStock: true }, { ml: 10, price: 3200, inStock: true }, { ml: 20, price: 5800, inStock: true }],
    isDecant: true, featured: true, rating: 4.7, reviews: 223
  },
  {
    id: "tf-lost-cherry",
    brand: "Tom Ford",
    name: "Lost Cherry",
    concentration: "EDP",
    releaseYear: 2018,
    perfumer: "Louise Turner",
    description: "A provocative and indulgent fragrance that captures the essence of ripe cherries preserved in liqueur. Lost Cherry opens with tart cherry and almond, blooms into jasmine and rose, and settles into a warm base of vanilla, tonka, and sandalwood.",
    notes: { top: ["Cherry", "Almond", "Liqueur"], middle: ["Jasmine", "Rose", "Plum"], base: ["Vanilla", "Tonka", "Sandalwood", "Cinnamon"] },
    family: "Gourmand Fruity",
    image: "images/lost-cherry.jpg",
    images: ["images/lost-cherry.jpg", "images/lost-cherry-2.jpg"],
    sizes: [{ ml: 2, price: 800, inStock: true }, { ml: 5, price: 1800, inStock: true }, { ml: 10, price: 3400, inStock: true }, { ml: 20, price: 6200, inStock: true }],
    isDecant: true, featured: false, rating: 4.5, reviews: 189
  },
  {
    id: "byredo-gypsy-water",
    brand: "Byredo",
    name: "Gypsy Water",
    concentration: "EDT",
    releaseYear: 2008,
    perfumer: "Jerome Epinette",
    description: "Inspired by the Romani culture and their free-spirited way of life. Gypsy Water is a captivating blend of bergamot, juniper berries, and pine needles, with a warm base of vanilla and amber. Fresh, earthy, and enchanting.",
    notes: { top: ["Bergamot", "Juniper", "Lemon"], middle: ["Pine", "Incense", "Orris"], base: ["Vanilla", "Amber", "Sandalwood"] },
    family: "Aromatic Fresh",
    image: "images/gypsy-water.jpg",
    images: ["images/gypsy-water.jpg", "images/gypsy-water-2.jpg"],
    sizes: [{ ml: 2, price: 750, inStock: true }, { ml: 5, price: 1600, inStock: true }, { ml: 10, price: 3000, inStock: true }, { ml: 20, price: 5500, inStock: true }],
    isDecant: true, featured: true, rating: 4.6, reviews: 178
  },
  {
    id: "kilian-angels-share",
    brand: "Kilian",
    name: "Angel's Share",
    concentration: "EDP",
    releaseYear: 2020,
    perfumer: "Benoist Lapouza",
    description: "Inspired by the angel's share — the portion of cognac that evaporates from oak barrels during aging. This warm, boozy gourmand features cognac, oak, and cinnamon with a heart of tonka and a rich vanilla base. Pure luxury in a bottle.",
    notes: { top: ["Cognac", "Cinnamon", "Pink Pepper"], middle: ["Oak", "Tonka", "Prune"], base: ["Vanilla", "Sandalwood", "Amber", "Cedar"] },
    family: "Oriental Gourmand",
    image: "images/angels-share.jpg",
    images: ["images/angels-share.jpg", "images/angels-share-2.jpg"],
    sizes: [{ ml: 2, price: 900, inStock: true }, { ml: 5, price: 2100, inStock: true }, { ml: 10, price: 3900, inStock: true }, { ml: 20, price: 7200, inStock: true }],
    isDecant: true, featured: true, rating: 4.9, reviews: 256
  },
  {
    id: "kilian-black-phantom",
    brand: "Kilian",
    name: "Black Phantom",
    concentration: "EDP",
    releaseYear: 2016,
    perfumer: "Sidonie Lancesseur",
    description: "A dangerously addictive gourmand that captures the duality of light and dark. Black Phantom opens with rum and coffee, reveals a heart of sugar cane and almond, and settles into a dark base of Indonesian patchouli and sandalwood.",
    notes: { top: ["Rum", "Coffee", "Cardamom"], middle: ["Sugar Cane", "Almond", "Coconut"], base: ["Patchouli", "Sandalwood", "Amber", "Musk"] },
    family: "Gourmand Spicy",
    image: "images/black-phantom.jpg",
    images: ["images/black-phantom.jpg", "images/black-phantom-2.jpg"],
    sizes: [{ ml: 2, price: 950, inStock: true }, { ml: 5, price: 2200, inStock: true }, { ml: 10, price: 4000, inStock: true }, { ml: 20, price: 7400, inStock: true }],
    isDecant: true, featured: false, rating: 4.7, reviews: 134
  },
  {
    id: "nishane-ani",
    brand: "Nishane",
    name: "Ani",
    concentration: "EDP",
    releaseYear: 2020,
    perfumer: "Cecile Zarokian",
    description: "A luxurious oriental vanilla fragrance named after the ancient Armenian capital. Ani opens with bergamot and pink pepper, blooms into a heart of jasmine and rose, and rests on a glorious base of vanilla, musk, and sandalwood.",
    notes: { top: ["Bergamot", "Pink Pepper", "Cardamom"], middle: ["Jasmine", "Rose", "Ginger"], base: ["Vanilla", "Musk", "Sandalwood", "Amber"] },
    family: "Oriental Vanilla",
    image: "images/ani.jpg",
    images: ["images/ani.jpg", "images/ani-2.jpg"],
    sizes: [{ ml: 2, price: 750, inStock: true }, { ml: 5, price: 1700, inStock: true }, { ml: 10, price: 3200, inStock: true }, { ml: 20, price: 5900, inStock: true }],
    isDecant: true, featured: true, rating: 4.8, reviews: 145
  },
  {
    id: "amouage-reflection-man",
    brand: "Amouage",
    name: "Reflection Man",
    concentration: "EDP",
    releaseYear: 2007,
    perfumer: "Lucas Sieuzac",
    description: "A masterful woody floral fragrance that embodies sophistication and grace. Reflection Man opens with rosemary and juniper, develops a heart of orris and jasmine, and settles into a warm base of cedar, sandalwood, and vetiver.",
    notes: { top: ["Rosemary", "Juniper", "Bergamot"], middle: ["Orris", "Jasmine", "Ylang Ylang"], base: ["Cedar", "Sandalwood", "Vetiver", "Musk"] },
    family: "Woody Floral",
    image: "images/reflection-man.jpg",
    images: ["images/reflection-man.jpg", "images/reflection-man-2.jpg"],
    sizes: [{ ml: 2, price: 850, inStock: true }, { ml: 5, price: 1900, inStock: true }, { ml: 10, price: 3600, inStock: true }, { ml: 20, price: 6600, inStock: true }],
    isDecant: true, featured: false, rating: 4.7, reviews: 156
  },
  {
    id: "xerjoff-erba-pura",
    brand: "Xerjoff",
    name: "Erba Pura",
    concentration: "EDP",
    releaseYear: 2019,
    perfumer: "Chris Maurice",
    description: "A vibrant and irresistible fruity gourmand that captures the essence of Mediterranean sunshine. Erba Pura bursts with Sicilian citrus, tropical fruits, and berries, layered over a creamy vanilla and musk base. Sweet, radiant, and utterly addictive.",
    notes: { top: ["Sicilian Lemon", "Bergamot", "Orange"], middle: ["Tropical Fruits", "Blackberry", "Strawberry"], base: ["Vanilla", "Musk", "Amber", "Sandalwood"] },
    family: "Fruity Gourmand",
    image: "images/erba-pura.jpg",
    images: ["images/erba-pura.jpg", "images/erba-pura-2.jpg"],
    sizes: [{ ml: 2, price: 800, inStock: true }, { ml: 5, price: 1800, inStock: true }, { ml: 10, price: 3400, inStock: true }, { ml: 20, price: 6300, inStock: true }],
    isDecant: true, featured: true, rating: 4.8, reviews: 212
  },
  {
    id: "creed-aventus-full",
    brand: "Creed",
    name: "Aventus (Full Bottle)",
    concentration: "EDP",
    releaseYear: 2010,
    perfumer: "Olivier Creed",
    description: "The complete Aventus experience in a full 100ml bottle. A masterpiece of modern perfumery that celebrates strength, vision, and success.",
    notes: { top: ["Pineapple", "Bergamot", "Black Currant", "Apple"], middle: ["Birch", "Jasmine", "Rose"], base: ["Musk", "Oakmoss", "Ambergris", "Vanilla"] },
    family: "Fruity Woody",
    image: "images/aventus-full.jpg",
    images: ["images/aventus-full.jpg", "images/aventus-full-2.jpg"],
    sizes: [{ ml: 50, price: 14000, inStock: true }, { ml: 100, price: 25000, inStock: true }],
    isDecant: false, featured: true, rating: 4.9, reviews: 234
  },
  {
    id: "mfk-baccarat-rouge-540-full",
    brand: "Maison Francis Kurkdjian",
    name: "Baccarat Rouge 540 (Full Bottle)",
    concentration: "EDP",
    releaseYear: 2015,
    perfumer: "Francis Kurkdjian",
    description: "The full bottle of the iconic Baccarat Rouge 540. A luminous and mesmerizing fragrance that has achieved legendary status worldwide.",
    notes: { top: ["Saffron", "Jasmine"], middle: ["Ambergris", "Cedar"], base: ["Fir", "Musk", "Amber"] },
    family: "Ambery Woody",
    image: "images/baccarat-rouge-full.jpg",
    images: ["images/baccarat-rouge-full.jpg", "images/baccarat-rouge-full-2.jpg"],
    sizes: [{ ml: 35, price: 16000, inStock: true }, { ml: 70, price: 28000, inStock: true }],
    isDecant: false, featured: true, rating: 4.9, reviews: 312
  },
  {
    id: "tf-tobacco-vanille-full",
    brand: "Tom Ford",
    name: "Tobacco Vanille (Full Bottle)",
    concentration: "EDP",
    releaseYear: 2007,
    perfumer: "Olivier Gillotin",
    description: "The full bottle of Tom Ford's modern classic. A rich, warm, and opulent fragrance combining sweet vanilla with smoky tobacco.",
    notes: { top: ["Tobacco", "Vanilla", "Chocolate"], middle: ["Tonka", "Cocoa", "White Honey"], base: ["Dried Fruits", "Wood", "Musk"] },
    family: "Gourmand Spicy",
    image: "images/tobacco-vanille-full.jpg",
    images: ["images/tobacco-vanille-full.jpg", "images/tobacco-vanille-full-2.jpg"],
    sizes: [{ ml: 50, price: 15000, inStock: true }, { ml: 100, price: 26000, inStock: true }],
    isDecant: false, featured: true, rating: 4.8, reviews: 267
  },
  {
    id: "lv-imagination-full",
    brand: "Louis Vuitton",
    name: "Imagination (Full Bottle)",
    concentration: "EDP",
    releaseYear: 2021,
    perfumer: "Jacques Cavallier",
    description: "The full bottle of Louis Vuitton's sparkling masterpiece. A sophisticated citrus fragrance with tea and ginger notes.",
    notes: { top: ["Bergamot", "Ginger", "Citrus"], middle: ["Tea", "Incense", "Neroli"], base: ["Amber", "Musk", "Cedar", "Sandalwood"] },
    family: "Citrus Aromatic",
    image: "images/imagination-full.jpg",
    images: ["images/imagination-full.jpg", "images/imagination-full-2.jpg"],
    sizes: [{ ml: 100, price: 35000, inStock: true }, { ml: 200, price: 55000, inStock: true }],
    isDecant: false, featured: true, rating: 4.8, reviews: 203
  },
  {
    id: "pdM-layton-full",
    brand: "Parfums de Marly",
    name: "Layton (Full Bottle)",
    concentration: "EDP",
    releaseYear: 2016,
    perfumer: "Hamid Merati-Kashani",
    description: "The full bottle of Layton, embodying the elegance and refinement of Parfums de Marly. A stunning blend of apple, lavender, and vanilla.",
    notes: { top: ["Apple", "Lavender", "Bergamot"], middle: ["Jasmine", "Rose", "Geranium"], base: ["Vanilla", "Sandalwood", "Guaiac Wood", "Musk"] },
    family: "Oriental Woody",
    image: "images/layton-full.jpg",
    images: ["images/layton-full.jpg", "images/layton-full-2.jpg"],
    sizes: [{ ml: 75, price: 18000, inStock: true }, { ml: 125, price: 27000, inStock: true }],
    isDecant: false, featured: false, rating: 4.8, reviews: 189
  },
  {
    id: "dior-sauvage-elixir-full",
    brand: "Dior",
    name: "Sauvage Elixir (Full Bottle)",
    concentration: "Elixir",
    releaseYear: 2021,
    perfumer: "Francois Demachy",
    description: "The full bottle of Dior's most intense fragrance. A concentrated, powerful, and profoundly aromatic masterpiece.",
    notes: { top: ["Cinnamon", "Nutmeg", "Grapefruit"], middle: ["Sage", "Lavender", "Cardamom"], base: ["Sandalwood", "Licorice", "Amber", "Cedar"] },
    family: "Aromatic Spicy",
    image: "images/sauvage-elixir-full.jpg",
    images: ["images/sauvage-elixir-full.jpg", "images/sauvage-elixir-full-2.jpg"],
    sizes: [{ ml: 60, price: 12000, inStock: true }, { ml: 100, price: 18000, inStock: true }],
    isDecant: false, featured: false, rating: 4.6, reviews: 178
  },
  {
    id: "creed-green-irish-tweed-full",
    brand: "Creed",
    name: "Green Irish Tweed (Full Bottle)",
    concentration: "EDP",
    releaseYear: 1985,
    perfumer: "Olivier Creed",
    description: "The full bottle of Creed's legendary aromatic fougere. Timeless, refined, and effortlessly sophisticated.",
    notes: { top: ["Lemon", "Verbena", "Mint"], middle: ["Iris", "Violet Leaf", "Orris"], base: ["Sandalwood", "Ambergris", "Cedar"] },
    family: "Aromatic Fougere",
    image: "images/green-irish-tweed-full.jpg",
    images: ["images/green-irish-tweed-full.jpg", "images/green-irish-tweed-full-2.jpg"],
    sizes: [{ ml: 50, price: 14000, inStock: true }, { ml: 100, price: 25000, inStock: true }],
    isDecant: false, featured: true, rating: 4.8, reviews: 198
  },
  {
    id: "tf-oud-wood-full",
    brand: "Tom Ford",
    name: "Oud Wood (Full Bottle)",
    concentration: "EDP",
    releaseYear: 2007,
    perfumer: "Richard Herpin",
    description: "The full bottle of Tom Ford's modern classic oud. Warm, woody, and impeccably refined.",
    notes: { top: ["Cardamom", "Rosewood", "Chinese Pepper"], middle: ["Oud", "Sandalwood", "Cedar"], base: ["Vanilla", "Amber", "Tonka", "Musk"] },
    family: "Woody Spicy",
    image: "images/oud-wood-full.jpg",
    images: ["images/oud-wood-full.jpg", "images/oud-wood-full-2.jpg"],
    sizes: [{ ml: 50, price: 18000, inStock: true }, { ml: 100, price: 32000, inStock: true }],
    isDecant: false, featured: true, rating: 4.7, reviews: 223
  },
  {
    id: "byredo-gypsy-water-full",
    brand: "Byredo",
    name: "Gypsy Water (Full Bottle)",
    concentration: "EDT",
    releaseYear: 2008,
    perfumer: "Jerome Epinette",
    description: "The full bottle of Byredo's captivating bestseller. Fresh, earthy, and enchanting.",
    notes: { top: ["Bergamot", "Juniper", "Lemon"], middle: ["Pine", "Incense", "Orris"], base: ["Vanilla", "Amber", "Sandalwood"] },
    family: "Aromatic Fresh",
    image: "images/gypsy-water-full.jpg",
    images: ["images/gypsy-water-full.jpg", "images/gypsy-water-full-2.jpg"],
    sizes: [{ ml: 50, price: 14000, inStock: true }, { ml: 100, price: 24000, inStock: true }],
    isDecant: false, featured: false, rating: 4.6, reviews: 178
  },
  {
    id: "kilian-angels-share-full",
    brand: "Kilian",
    name: "Angel's Share (Full Bottle)",
    concentration: "EDP",
    releaseYear: 2020,
    perfumer: "Benoist Lapouza",
    description: "The full bottle of Kilian's award-winning gourmand. A warm, boozy masterpiece of cognac and vanilla.",
    notes: { top: ["Cognac", "Cinnamon", "Pink Pepper"], middle: ["Oak", "Tonka", "Prune"], base: ["Vanilla", "Sandalwood", "Amber", "Cedar"] },
    family: "Oriental Gourmand",
    image: "images/angels-share-full.jpg",
    images: ["images/angels-share-full.jpg", "images/angels-share-full-2.jpg"],
    sizes: [{ ml: 50, price: 20000, inStock: true }, { ml: 100, price: 36000, inStock: true }],
    isDecant: false, featured: true, rating: 4.9, reviews: 256
  },
  {
    id: "nishane-ani-full",
    brand: "Nishane",
    name: "Ani (Full Bottle)",
    concentration: "EDP",
    releaseYear: 2020,
    perfumer: "Cecile Zarokian",
    description: "The full bottle of Nishane's luxurious oriental vanilla. A glorious blend of vanilla, musk, and sandalwood.",
    notes: { top: ["Bergamot", "Pink Pepper", "Cardamom"], middle: ["Jasmine", "Rose", "Ginger"], base: ["Vanilla", "Musk", "Sandalwood", "Amber"] },
    family: "Oriental Vanilla",
    image: "images/ani-full.jpg",
    images: ["images/ani-full.jpg", "images/ani-full-2.jpg"],
    sizes: [{ ml: 50, price: 16000, inStock: true }, { ml: 100, price: 28000, inStock: true }],
    isDecant: false, featured: true, rating: 4.8, reviews: 145
  },
  {
    id: "amouage-reflection-man-full",
    brand: "Amouage",
    name: "Reflection Man (Full Bottle)",
    concentration: "EDP",
    releaseYear: 2007,
    perfumer: "Lucas Sieuzac",
    description: "The full bottle of Amouage's masterful woody floral. Sophistication and grace in every spray.",
    notes: { top: ["Rosemary", "Juniper", "Bergamot"], middle: ["Orris", "Jasmine", "Ylang Ylang"], base: ["Cedar", "Sandalwood", "Vetiver", "Musk"] },
    family: "Woody Floral",
    image: "images/reflection-man-full.jpg",
    images: ["images/reflection-man-full.jpg", "images/reflection-man-full-2.jpg"],
    sizes: [{ ml: 50, price: 18000, inStock: true }, { ml: 100, price: 32000, inStock: true }],
    isDecant: false, featured: false, rating: 4.7, reviews: 156
  }
];

const brandsList = ["Creed","Nishane","Xerjoff","Amouage","Parfums de Marly","Mancera","Montale","Maison Francis Kurkdjian","Roja Parfums","Initio","Louis Vuitton","Tom Ford","Dior","Chanel","Byredo","Kilian"];
const fragranceFamilies = ["Fruity Woody","Chypre Fruity","Oriental Fougere","Oriental Spicy","Oriental Woody","Woody Citrus","Oriental Gourmand","Ambery Woody","Citrus Aromatic","Gourmand Spicy","Aromatic Spicy","Woody Aromatic","Aromatic Fougere","Aromatic Aquatic","Woody Spicy","Gourmand Fruity","Aromatic Fresh","Oriental Vanilla","Woody Floral","Fruity Gourmand"];
const allNotes = ["Pineapple","Bergamot","Black Currant","Apple","Grapefruit","Birch","Jasmine","Rose","Musk","Oakmoss","Ambergris","Vanilla","Cedar","Patchouli","Sandalwood","Amber","Lemon","Lavender","Honey","Tobacco","Cinnamon","Tonka","Saffron","Oregano","Frankincense","Leather","Myrrh","Pepper","Ginger","Tea","Incense","Neroli","Chocolate","Cocoa","Nutmeg","Sage","Cardamom","Mint","Licorice","Juniper","Rum","Pomegranate","White Honey","Benzoin","Oud","Verbena","Iris","Violet Leaf","Mandarin","Green Tea","Galbanum","Petitgrain","Rosewood","Cherry","Almond","Liqueur","Plum","Pine","Orris","Coconut","Sugar Cane","Coffee","Cognac","Prune","Strawberry","Blackberry","Tropical Fruits","Sicilian Lemon","Orange","Rosemary","Ylang Ylang","Vetiver","Coconut"];
const priceRanges = [{ label: "Under 1000 BDT", min: 0, max: 1000 }, { label: "1000 - 2000 BDT", min: 1000, max: 2000 }, { label: "2000 - 4000 BDT", min: 2000, max: 4000 }, { label: "4000 - 6000 BDT", min: 4000, max: 6000 }, { label: "Above 6000 BDT", min: 6000, max: Infinity }];

const testimonials = [
  { id: 1, name: "Rafi Hossain", location: "Dhaka", rating: 5, text: "Absolutely blown away by the quality! The Aventus decant I ordered is incredible\u2014perfect projection and longevity. Will definitely be ordering more.", avatar: "images/avatar-1.jpg" },
  { id: 2, name: "Sadia Islam", location: "Chittagong", rating: 5, text: "Noble Notes is a game changer for fragrance lovers in Bangladesh. Finally access to niche fragrances at reasonable prices. The packaging was beautiful too!", avatar: "images/avatar-2.jpg" },
  { id: 3, name: "Tanvir Ahmed", location: "Dhaka", rating: 5, text: "The Baccarat Rouge 540 decant I received is 100% authentic. I've owned the original and this is identical. Fast delivery and excellent customer service.", avatar: "images/avatar-3.jpg" },
  { id: 4, name: "Nusrat Jahan", location: "Sylhet", rating: 4, text: "Love the curated selection! Discovered Layton through Noble Notes and it's become my signature scent. The 5ml decant lasted me 3 weeks.", avatar: "images/avatar-4.jpg" },
  { id: 5, name: "Kazi Fahim", location: "Dhaka", rating: 5, text: "Best place for decants in Bangladesh! The glass bottles with sprayers are premium quality. Communication via WhatsApp was smooth and professional.", avatar: "images/avatar-5.jpg" }
];

function getProductById(id) {
  return products.find(p => p.id === id);
}

function getDecants() {
  return products.filter(p => p.isDecant);
}

function getFullBottles() {
  return products.filter(p => !p.isDecant);
}

function getFeaturedProducts() {
  return products.filter(p => p.featured);
}
